name: Deploy to GitHub Pages

# Запуск при push в main (или замените на нужную ветку)
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write       # для деплоя на Pages
      id-token: write    # для аутентификации

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/setup-pages@v3

      - name: Prepare site for GitHub Pages
        run: |
          cp "RM-75 Converter.html" index.html
          echo "No build step for static HTML"

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./         # путь к директории с сайтом (корень репозитория)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
